const AC = [
  {
    number: 1,
    name: "Panasonic",
    nameDescription:
      "Panasonic 7 in 1 Convertible with True AI Mode 1.5 Ton 3 Star Split Inverter AC with Wi-fi Connect - White  (CS-SU18ZKYWT/CU-SU18ZKYWT, Copper Condenser)",
    ratingStar: 4.1,
    ratingNumber: "25,279",
    reviewNumber: "2,554",
    img: "/ProductList/Panasonic.png",
    powerUsage: "1002.31",
    roomSize: "111-150 sqft",
    productWarranty: 1,
    pcbWarranty: 1,
    compressorWarranty: 10,
    price: "36,990",
    originalPrice: "55,400",
    offer: "33",
    date: "Tomorrow",
    hotDeal: "yes",
    cashback: "5,100",
    bankOffer: "no",
  },
  {
    number: 2,
    name: "Voltas",
    nameDescription:
      "Voltas 1.5 Ton 3 Star Split Inverter AC - White  (183V CAX(4503692), Copper Condenser)",
    ratingStar: 4,
    ratingNumber: "17,081",
    reviewNumber: "876",
    img: "/ProductList/Voltas.png",
    powerUsage: "975.26",
    roomSize: "111-150 sqft",
    productWarranty: 1,
    pcbWarranty: 0,
    compressorWarranty: 10,
    price: "33,990",
    originalPrice: "62,990",
    offer: "46",
    date: "Tomorrow",
    hotDeal: "no",
    cashback: "5,100",
    bankOffer: "yes",
  },
  {
    number: 3,
    name: "Daikin",
    nameDescription:
      "Daikin 0.8 Ton 3 Star Split AC - White  (FTL30UV16V1/RL30UV16V1, Copper Condenser)",
    ratingStar: 4.2,
    ratingNumber: "14,937",
    reviewNumber: "1,136",
    img: "/ProductList/Daikin.png",
    powerUsage: "574.39",
    roomSize: "90 sqft or below",
    productWarranty: 1,
    pcbWarranty: 0,
    compressorWarranty: 5,
    price: "25,990",
    originalPrice: "38,100",
    offer: "31",
    date: "Tomorrow",
    hotDeal: "yes",
    cashback: "5,100",
    bankOffer: "no",
  },
  {
    number: 4,
    name: "LG",
    nameDescription:
      "LG AI Convertible 6-in-1 Cooling 2024 Model 1.5 Ton 3 Star Split Dual Inverter HD Filter with Anti-Virus Protection,VIRAAT Mode, Diet Mode & ADC Sensor AC - White  (TS-Q18JNXE3, Copper Condenser)",
    ratingStar: 4.1,
    ratingNumber: "40,935",
    reviewNumber: "3,646",
    img: "/ProductList/LG.png",
    powerUsage: "852.44",
    roomSize: "111-150 sqft",
    productWarranty: 1,
    pcbWarranty: 5,
    compressorWarranty: 10,
    price: "36,990",
    originalPrice: "78,990",
    offer: "53",
    date: "Tomorrow",
    hotDeal: "yes",
    cashback: "5,100",
    bankOffer: "no",
  },
];

export { AC };
