// AC Data
const AC = [
  {
    number: 1,
    name: "Panasonic",
    nameDescription:
      "Panasonic 7 in 1 Convertible with True AI Mode 1.5 Ton 3 Star Split Inverter AC with Wi-fi Connect - White  (CS-SU18ZKYWT/CU-SU18ZKYWT, Copper Condenser)",
    ratingStar: 4.1,
    ratingNumber: "25,279",
    reviewNumber: "2,554",
    img: "/ProductList/Panasonic.png",
    powerUsage: "1002.31",
    roomSize: "111-150 sqft",
    productWarranty: 1,
    pcbWarranty: 1,
    compressorWarranty: 10,
    price: "80,990",
    originalPrice: "55,400",
    offer: "33",
    date: "Tomorrow",
    hotDeal: "yes",
    cashback: "5,100",
    bankOffer: "no",
  },
  {
    number: 2,
    name: "Voltas",
    nameDescription:
      "Voltas 1.5 Ton 3 Star Split Inverter AC - White  (183V CAX(4503692), Copper Condenser)",
    ratingStar: 4,
    ratingNumber: "17,081",
    reviewNumber: "876",
    img: "/ProductList/Voltas.png",
    powerUsage: "975.26",
    roomSize: "111-150 sqft",
    productWarranty: 1,
    pcbWarranty: 0,
    compressorWarranty: 10,
    price: "42,990",
    originalPrice: "62,990",
    offer: "46",
    date: "Tomorrow",
    hotDeal: "no",
    cashback: "5,100",
    bankOffer: "yes",
  },
  {
    number: 3,
    name: "Daikin",
    nameDescription:
      "Daikin 0.8 Ton 3 Star Split AC - White  (FTL30UV16V1/RL30UV16V1, Copper Condenser)",
    ratingStar: 4.2,
    ratingNumber: "14,937",
    reviewNumber: "1,136",
    img: "/ProductList/Daikin.png",
    powerUsage: "574.39",
    roomSize: "90 sqft or below",
    productWarranty: 1,
    pcbWarranty: 0,
    compressorWarranty: 5,
    price: "25,990",
    originalPrice: "38,100",
    offer: "31",
    date: "Tomorrow",
    hotDeal: "yes",
    cashback: "5,100",
    bankOffer: "no",
  },
  {
    number: 4,
    name: "LG",
    nameDescription:
      "LG AI Convertible 6-in-1 Cooling 2024 Model 1.5 Ton 3 Star Split Dual Inverter HD Filter with Anti-Virus Protection,VIRAAT Mode, Diet Mode & ADC Sensor AC - White  (TS-Q18JNXE3, Copper Condenser)",
    ratingStar: 4.1,
    ratingNumber: "40,935",
    reviewNumber: "3,646",
    img: "/ProductList/LG.png",
    powerUsage: "852.44",
    roomSize: "111-150 sqft",
    productWarranty: 1,
    pcbWarranty: 5,
    compressorWarranty: 10,
    price: "36,990",
    originalPrice: "78,990",
    offer: "53",
    date: "Tomorrow",
    hotDeal: "yes",
    cashback: "5,100",
    bankOffer: "no",
  },
];

// Tv Data
const TV = [
  {
    number: 1,
    name: "TCL",
    nameDescription:
      "TCL L4B 79.97 cm (32 inch) HD Ready LED Smart Android TV 2024 Edition with Metallic Bezel Less and Chromecast built-in  (32L4B)",
    ratingStar: 4.1,
    ratingNumber: "28,475",
    reviewNumber: "2,371",
    img: "/ProductList/TCLTV.png",
    operatingSystem: "Android",
    pixels: "HD Ready 1366 X 768 Pixels",
    launch: 2024,
    productWarranty: 1,
    additionalWarranty: 0,
    price: "8,990",
    originalPrice: "20,990",
    offer: "57",
    date: "Tomorrow",
    hotDeal: "yes",
    cashback: "3,700",
    bankOffer: "no",
  },
  {
    number: 2,
    name: "Mi",
    nameDescription:
      "Mi by Xiaomi A Series 80 cm (32 inch) HD Ready LED Smart Google TV 2024 Edition with 200+ Free Channels |Dolby Audio | DTS:HD|DTS Virtual: X| Vivid Picture Engine| Dual Band Wi-Fi| Bluetooth 5.0 Metallic Bezel Less and Chromecast built-in  (32L4B)",
    ratingStar: 4.3,
    ratingNumber: "1,74,973",
    reviewNumber: "13,371",
    img: "/ProductList/MI.png",
    operatingSystem: "Google Tv",
    pixels: "HD Ready 1366 X 768 Pixels",
    launch: 2022,
    productWarranty: 1,
    additionalWarranty: 1,
    price: "13,999",
    originalPrice: "24,999",
    offer: "44",
    date: "Tomorrow",
    hotDeal: "no",
    cashback: "5,400 ",
    bankOffer: "no",
  },
  {
    number: 3,
    name: "Samsung",
    nameDescription:
      "SAMSUNG 80 cm (32 Inch) HD Ready LED Smart Tizen TV with Bezel-Free Design | 300+ Free Channels | PurColor | Hyper Real Picture Engine | Triple Protection | SmartThings App Support | TV Key | Connect Share (HDD) | ConnectShare (USB 2.0)  (UA32T4380AKXXL)",
    ratingStar: 4.3,
    ratingNumber: "1.53,099",
    reviewNumber: "11,245",
    img: "/ProductList/samsung.png",
    operatingSystem: "Tizen",
    pixels: " HD Ready 1366 X 768 Pixels",
    launch: 2024,
    productWarranty: 1,
    additionalWarranty: 1,
    price: "15,990",
    originalPrice: "18,990",
    offer: "19",
    date: "Tomorrow",
    hotDeal: "yes",
    cashback: "5,400",
    bankOffer: "yes",
  },
  {
    number: 4,
    name: "LG",
    nameDescription:
      "LG 32LMBPTC 80 cm (32 inch) HD Ready LED Smart WebOS TV with Quad Core Processor, Active HDR, 60 Hz Refresh Rate, DTS Virtual:X, Dolby Audio  (32LM563BPTC)",
    ratingStar: 4.3,
    ratingNumber: "24,210",
    reviewNumber: "1,564",
    img: "/ProductList/LGTV.png",
    operatingSystem: "Web OS",
    pixels: "HD Ready 1366 X 768 Pixels",
    launch: 2020,
    productWarranty: 1,
    price: "43,490",
    originalPrice: "54,990",
    offer: "46",
    date: "Tomorrow",
    hotDeal: "no",
    cashback: "5,400 ",
    bankOffer: "no",
  },
  {
    number: 5,
    name: "Toshiba",
    nameDescription:
      "TOSHIBA C350NP 189 cm (75 inch) Ultra HD (4K) LED Smart Google TV 2024 Edition with Dolby Vision Atmos and REGZA Engine ZR  (75C350NP)",
    ratingStar: 4.3,
    ratingNumber: "5,581",
    reviewNumber: "975",
    img: "/ProductList/Toshiba.png",
    operatingSystem: "Google TV",
    pixels: "Ultra HD (4K) 3840 X 2160 Pixels",
    launch: 2024,
    productWarranty: 1,
    price: "76,229",
    originalPrice: "1,14,999",
    offer: "33",
    date: "Tomorrow",
    hotDeal: "yes",
    cashback: "3,700",
    bankOffer: "no",
  },
];

const Gadgets = [
  {
    number: 1,
    name: "Samsung",
    nameDescription: "SAMSUNG Galaxy F05 (Twilight Blue, 64 GB)  (4 GB RAM)",
    ratingStar: 4.2,
    size: "w-36 mt-6",
    ratingNumber: "24,743",
    reviewNumber: "1,403",
    img: "/ProductList/SamsungMob.png",
    ram: "4GB",
    rom: "64GB",
    expandable: "upto 1TB",
    display: "17.12 cm (6.74 inch) HD+ Dispaly",
    rearCam: "50MP + 2MP",
    frontCam: "8MP",
    battery: "5000mAh ",
    processor: " Helio G85",
    productWarranty: "1 year",
    AccessoryWarranty: "6 month",
    price: "6,249",
    originalPrice: "9,999",
    offer: "37",
    date: "Tomorrow",
    hotDeal: "yes",
    cashback: "5,700 ",
    bankOffer: "no",
  },
  {
    number: 2,
    name: "Motorola",
    nameDescription: "Motorola G85 5G (Cobalt Blue, 256 GB)  (12 GB RAM)",
    ratingStar: 4.4,
    size: "w-36 mt-6",
    ratingNumber: "46,743",
    reviewNumber: "2,403",
    img: "/ProductList/Motorola.png",
    ram: "12GB",
    rom: "256GB",
    expandable: "",
    display: "16.94 cm (6.67 inch) Full HD+ Dispaly",
    rearCam: "50MP + 8MP",
    frontCam: "32MP",
    battery: "5000mAh ",
    processor: " 6s Gen 3",
    productWarranty: "1 year",
    AccessoryWarranty: "6 month",
    price: "18,999",
    originalPrice: "22,999",
    offer: "17",
    date: "19th Jan",
    hotDeal: "no",
    cashback: "17,850 ",
    bankOffer: "yes",
  },
  {
    number: 3,
    name: "Apple",
    nameDescription: "Apple iPhone 16 (Black, 128 GB)",
    ratingStar: 4.6,
    size: "w-36 mt-6",
    ratingNumber: "2,260",
    reviewNumber: "85",
    img: "/ProductList/Apple.png",
    ram: "",
    rom: "64GB",
    expandable: "",
    display: "15.49 cm (6.1 inch) Super Retina XDR Dispaly",
    rearCam: "48MP + 12MP",
    frontCam: "12MP",
    battery: "",
    processor: " A18 Chip, 6 Core ",
    productWarranty: "1 year",
    AccessoryWarranty: "1 Year",
    price: "67,999",
    originalPrice: "79,900",
    offer: "14",
    date: "Tomorrow",
    hotDeal: "no",
    cashback: "61,600 ",
    bankOffer: "yes",
  },
  {
    number: 4,
    name: "SamsungS24",
    nameDescription:
      "SAMSUNG Galaxy S24 Ultra 5G (Titanium Black, 256 GB)  (12 GB RAM)",
    ratingStar: 4.6,
    size: "w-44 mt-6",
    ratingNumber: "2,512",
    reviewNumber: "278",
    img: "/ProductList/Samsungs24.png",
    ram: "12GB",
    rom: "256GB",
    expandable: "",
    display: "17.27 cm (6.8 inch) QUAD HD+ Dispaly",
    rearCam: "200MP + 50MP + 12MP + 10MP",
    frontCam: "12MP",
    battery: "5000mAh ",
    processor: " Snapdragon 8 Gen 3",
    productWarranty: "1 year",
    AccessoryWarranty: "6 month",
    price: "1,21,999",
    originalPrice: "1,34,999",
    offer: "9%",
    date: "19th Jan",
    hotDeal: "yes",
    cashback: "5,700 ",
    bankOffer: "no",
  },
  {
    number: 5,
    name: "SamsungS23",
    nameDescription:
      "SAMSUNG Galaxy S23 5G (Cream, 256 GB)  (8 GB RAM)#JustHere",
    ratingStar: 4.6,
    size: "w-40 mt-6",
    ratingNumber: "68,512",
    reviewNumber: "4,729",
    img: "/ProductList/Samsungs23.png",
    ram: "8GB",
    rom: "256GB",
    expandable: "",
    display: "15.49 cm (6.1 inch) Full HD+ Dispaly",
    rearCam: "50MP + 10MP + 12MP",
    frontCam: "12MP",
    battery: "3900mAh ",
    processor: " Snapdragon 8 Gen 2",
    productWarranty: "1 year",
    AccessoryWarranty: "6 month",
    price: "41,999",
    originalPrice: "95,999",
    offer: "56",
    date: "19th Jan",
    hotDeal: "yes",
    cashback: "39,000 ",
    bankOffer: "no",
  },
  {
    number: 6,
    name: "GooglePixel",
    nameDescription: "Google Pixel 9 (Porcelain, 256 GB)  (12 GB RAM)",
    ratingStar: 4.6,
    size: "w-44 mt-6",
    ratingNumber: "1,876",
    reviewNumber: "202",
    img: "/ProductList/Pixel9.png",
    ram: "12GB",
    rom: "256GB",
    expandable: "",
    display: "16.0 cm (6.3 inch) Dispaly",
    rearCam: "50MP + 48MP",
    frontCam: "10.5MP",
    battery: "4700mAh ",
    processor: " Google Tensor G4",
    productWarranty: "1 year",
    AccessoryWarranty: "",
    price: "74,999",
    originalPrice: "79,999",
    offer: "6%",
    date: "Tomorrow",
    hotDeal: "yes",
    cashback: "63,000 ",
    bankOffer: "no",
  },
];

const HOME = [
  {
    number: 1,
    name: "Samsung",
    nameDescription:
      "SAMSUNG 7.5 Kg Semi Automatic Top Load Washing Machine Grey, Red  (WT75B3200RR/TL)",
    ratingStar: 4.4,
    size: "w-40 ",
    ratingNumber: "38,458",
    reviewNumber: "2,688",
    img: "/ProductList/SamWash.png",
    rpm: "1300",
    productWarranty: "2 year",
    motorWarranty: "2 Year",
    star: 5,
    price: "11,499",
    originalPrice: "15,800",
    offer: "27",
    date: "Tomorrow",
    hotDeal: "yes",
    cashback: "2,850 ",
    bankOffer: "no",
  },
  {
    number: 2,
    name: "Reliance",
    nameDescription: "Reliance 7.5 kg Washer only Red, White  (RGT750WR)",
    ratingStar: 4.7,
    size: "w-36 ",
    ratingNumber: "24",
    reviewNumber: "2",
    img: "/ProductList/Reliance.png",
    rpm: "1350",
    productWarranty: "1 year",
    motorWarranty: "1 Year",
    star: 1,
    price: "5,099",
    originalPrice: "8,499",
    offer: "40",
    date: "Tomorrow",
    hotDeal: "no",

    bankOffer: "yes",
  },
  {
    number: 3,
    name: "IFB",
    nameDescription:
      "IFB 7 kg Powered by AI, 5 Star, 4 years Comprehensive Warranty with 2x Steam Cycle Fully Automatic Front Load Washing Machine with In-built Heater Brown  (DIVA AQUA MXS 7010)",
    ratingStar: 4.4,
    size: "w-36  ",
    ratingNumber: "85,452",
    reviewNumber: "8,509",
    img: "/ProductList/IFB.png",
    rpm: "1000",
    builtinHeater: "yes",
    productWarranty: "4 year",
    motorWarranty: "10 Year",
    star: 5,
    price: "26,990",
    originalPrice: "36,990",
    offer: "27",
    date: "Tomorrow",
    hotDeal: "yes",
    cashback: "2,850 ",
    bankOffer: "no",
  },
  {
    number: 4,
    name: "Samsung",
    nameDescription:
      "SAMSUNG 12 kg 5star, AI Ecobubble, Super Speed, Wi-Fi, Hygiene Steam,Digital Inverter Fully Automatic Front Load Washing Machine with In-built Heater Black, Grey  (WW12DG5B24AXTL)",
    ratingStar: 4.4,
    size: "w-44 ",
    ratingNumber: "15,458",
    reviewNumber: "1,163",
    img: "/ProductList/SamWash2.png",
    rpm: "1400",
    productWarranty: "2 year",
    motorWarranty: "20 Year",
    builtinHeater: "yes",
    wifi: "yes",
    star: 5,
    price: "43,990",
    originalPrice: "52,800",
    offer: "16",
    date: "Tomorrow",
    hotDeal: "no",
    cashback: "2,850 ",
    bankOffer: "yes",
  },
];

const KITCHEN = [
  {
    number: 1,
    name: "Niptron",
    nameDescription:
      "NIPTRON Electronic Digital 10Kg Weight Scale Kitchen Measuring for Fruits, Vegetable Weighing Scale  (White)24AXTL)",
    ratingStar: 4.4,
    color: "White",
    size: "w-60 mb-1 mx-auto",
    ratingNumber: "15,458",
    reviewNumber: "1,163",
    img: "/ProductList/Weight.png",
    rpm: "1400",
    productWarranty: "2 year",
    motorWarranty: "20 Year",
    builtinHeater: "yes",
    wifi: "yes",
    star: 5,
    price: "309",
    originalPrice: "999",
    offer: "69",
    freeDelivery: "yes",
    hotDeal: "no",

    bankOffer: "no",
  },
  {
    number: 2,
    name: "Pigeon",
    nameDescription:
      "Pigeon 20-Litre Oven Toaster Grill (OTG)  (16321/16132, Black)",
    ratingStar: 3.9,
    color: "16321 | 16132, Black",
    size: "w-60 mx-auto",
    ratingNumber: "21,707",
    reviewNumber: "1,163",
    img: "/ProductList/Oven.png",

    productWarranty: "2 year",
    motorWarranty: "20 Year",
    builtinHeater: "yes",
    wifi: "yes",
    star: 5,
    price: "3,299",
    originalPrice: "5,795",
    offer: "43",
    freeDelivery: "no",
    hotDeal: "no",

    bankOffer: "yes",
  },
  {
    number: 3,
    name: "Vyog",
    nameDescription:
      "vyog SF-400 A, 10Kg Weight Machine with Fast Response Sensor for Shop, Home Weighing Scale  (White)",
    ratingStar: 3.7,
    color: "White",
    size: "w-72  mx-auto mb-1",
    ratingNumber: "527",
    reviewNumber: "1,163",
    img: "/ProductList/Vyog.png",
    rpm: "1400",
    productWarranty: "2 year",
    motorWarranty: "20 Year",
    builtinHeater: "yes",
    wifi: "yes",
    star: 5,
    price: "378",
    originalPrice: "975",
    offer: "61",
    freeDelivery: "yes",
    hotDeal: "no",

    bankOffer: "no",
  },
  {
    number: 4,
    name: "Pigeon",
    nameDescription:
      "Pigeon Healthifry Digital with 360 High Speed Air Circulation Technology 1200 W with Non-Stick Basket - Green Air Fryer  (4.2 L)",
    ratingStar: 4,
    color: "4.2L",
    size: "w-52 mx-auto",
    ratingNumber: "33,541",
    reviewNumber: "1,163",
    img: "/ProductList/PigeonFryer.png",
    rpm: "1400",
    productWarranty: "2 year",
    motorWarranty: "20 Year",
    builtinHeater: "yes",
    wifi: "yes",
    star: 5,
    price: "2,799",
    originalPrice: "5,995",
    offer: "53",
    freeDelivery: "yes",
    hotDeal: "no",

    bankOffer: "yes",
  },
  {
    number: 5,
    name: "Pigeon",
    nameDescription: "Pigeon Favourite Electric Kettle  (1.2 L, Silver, Black)",
    ratingStar: 4,
    color: "1.2L Silver, Black",
    size: "w-52 mb-2 mx-auto",
    ratingNumber: "62,599",
    reviewNumber: "1,163",
    img: "/ProductList/PigeonKettle.png",
    rpm: "1400",
    productWarranty: "2 year",
    motorWarranty: "20 Year",
    builtinHeater: "yes",
    wifi: "yes",
    star: 5,
    price: "749",
    originalPrice: "1,595",
    offer: "53",
    freeDelivery: "yes",
    hotDeal: "yes",

    bankOffer: "no",
  },
  {
    number: 6,
    name: "Agaro",
    nameDescription:
      "AGARO Imperial Espresso Coffee Maker, Coffee Machine, 15 Bars, 6 Cups Coffee Maker  (Silver)",
    ratingStar: 4.2,
    color: "Silver",
    size: "w-56 mx-auto",
    ratingNumber: "287",
    reviewNumber: "1,163",
    img: "/ProductList/Agaro.png",
    rpm: "1400",
    productWarranty: "2 year",
    motorWarranty: "20 Year",
    builtinHeater: "yes",
    wifi: "yes",
    star: 5,
    price: "9,499",
    originalPrice: "16,990",
    offer: "44",
    freeDelivery: "yes",
    hotDeal: "yes",

    bankOffer: "no",
  },
  {
    number: 7,
    name: "Pigeon",
    nameDescription:
      "Pigeon Favourite Electric Kettle  (1.5 L, Silver, Black)#JustHere",
    ratingStar: 4.1,
    color: "1.5L Silver, Black",
    size: "w-60 mb-1 mx-auto",
    ratingNumber: "6,17,255",
    reviewNumber: "1,163",
    img: "/ProductList/PigeonElectric.png",
    rpm: "1400",
    productWarranty: "2 year",
    motorWarranty: "20 Year",
    builtinHeater: "yes",
    wifi: "yes",
    star: 5,
    price: "499",
    originalPrice: "1,245",
    offer: "59",
    freeDelivery: "no",
    hotDeal: "no",

    bankOffer: "yes",
  },
  {
    number: 8,
    name: "Flipkart",
    nameDescription:
      "Flipkart SmartBuy PowerChef Premium 500 W Mixer Grinder  (FKSBMG50AIDHNBW / FKSBMG500AIDHNBW | 3 Jars | with 1 year extended warranty | White, Navy Blue)",
    ratingStar: 4.4,
    color:
      "FKSBMG50AIDHNBW / FKSBMG500AIDHNBW | 3 Jars | with 1 year extended warranty | White, Navy Blue",
    size: "w-56 mx-auto",
    ratingNumber: "1,29,075",
    reviewNumber: "1,163",
    img: "/ProductList/Flipkart.png",
    rpm: "1400",
    productWarranty: "2 year",
    motorWarranty: "20 Year",
    builtinHeater: "yes",
    wifi: "yes",
    star: 5,
    price: "1,099",
    originalPrice: "2,799",
    offer: "60",
    freeDelivery: "no",
    hotDeal: "no",
    cashback: "180 ",
    bankOffer: "no",
  },
  {
    number: 9,
    name: "Philips",
    nameDescription: "PHILIPS HD2582/00 830 W Pop Up Toaster  (White)",
    ratingStar: 4.5,
    color: "White",
    size: "w-60 mb-7 mx-auto",
    ratingNumber: "7,135",
    reviewNumber: "1,163",
    img: "/ProductList/Philips.png",
    rpm: "1400",
    productWarranty: "2 year",
    motorWarranty: "20 Year",
    builtinHeater: "yes",
    wifi: "yes",
    star: 5,
    price: "2,450",
    originalPrice: "2,795",
    offer: "12",
    freeDelivery: "yes",
    hotDeal: "no",
    cashback: "2,850 ",
    bankOffer: "yes",
  },
  {
    number: 10,
    name: "Philips",
    nameDescription:
      "NIPTRON Electronic Digital 10Kg Weight Scale Kitchen Measuring for Fruits, Vegetable Weighing Scale  (White)24AXTL)",
    ratingStar: 4.1,
    color: "Black",
    size: "w-44 mb-2 mx-auto",
    ratingNumber: "456",
    reviewNumber: "1,163",
    img: "/ProductList/PhilipsGrind.png",
    rpm: "1400",
    productWarranty: "2 year",
    motorWarranty: "20 Year",
    builtinHeater: "yes",
    wifi: "yes",
    star: 5,
    price: "53,247",
    originalPrice: "43,895",
    offer: "16",
    freeDelivery: "yes",
    hotDeal: "no",
    cashback: "2,850 ",
    bankOffer: "yes",
  },
];

const PC = [
  {
    number: 1,
    name: "hp",
    nameDescription:
      "HP 15s Intel Core i3 12th Gen 1215U - (8 GB/512 GB SSD/Windows 11 Home) 15s-fy5003TU Thin and Light Laptop  (15.6 inch, Natural Silver, 1.69 Kg, With MS Office)",
    ratingStar: 4.1,
    ram: "8GB RAM DDR4",
    size: "w-60 mt-10",
    ratingNumber: "6,168",
    reviewNumber: "367",
    img: "/ProductList/hp.png",
    processor: "Intel Core i3 Processor",
    display: "39.62 cm (15.6 inch) Display",
    productWarranty: "1 year",
    operatingSystem: "Windows 11",
    ssd: "512 GB",
    wifi: "yes",
    price: "34,990",
    originalPrice: "51,266",
    offer: "31",
    freeDelivery: "yes",
    hotDeal: "yes",
    cashback: "25,000 ",
    bankOffer: "no",
    date: "Tomorrow",
  },
  {
    number: 2,
    name: "Acer",
    nameDescription:
      "Acer Swift Go 14 AMD Ryzen 5 Hexa Core 7430U - (16 GB/512 GB SSD/Windows 11 Home) SFG14-41-R6G9 Thin and Light Laptop  (14 Inch, Pure Silver, 1.25 Kg, With MS Office)",
    ratingStar: 4.3,
    ram: "16GB LPDDR4X RAM",
    size: "w-64 mt-10",
    ratingNumber: "468",
    reviewNumber: "53",
    img: "/ProductList/AcerGo.png",
    processor: "AMD Ryzen 5 Hexa Core Processor",
    display: "35.56 cm (14 inch) Display",
    productWarranty: "1 year",
    operatingSystem: "Windows 11",
    ssd: "512 GB",
    wifi: "yes",
    price: "39,990",
    originalPrice: "69,266",
    offer: "45",
    freeDelivery: "yes",
    hotDeal: "no",
    cashback: "25,000 ",
    bankOffer: "yes",
    carryonWarranty: "1 Year",
    date: "Tomorrow",
  },
  {
    number: 3,
    name: "samsung",
    nameDescription:
      "SAMSUNG Galaxy Book4 Intel Core i5 13th Gen 1335U - (16 GB/512 GB SSD/Windows 11 Home) NP750XGJ-KG2IN / NP750XGJ-LG2IN Thin and Light Laptop  (15.6 Inch, Gray, 1.55 Kg, With MS Office)",
    ratingStar: 4.5,
    ram: "16GB LPDDR4X RAM",
    size: "w-60 mt-10",
    ratingNumber: "4,117",
    reviewNumber: "378",
    img: "/ProductList/SamsungLap.png",
    processor: "Intel Core i5 Processor",
    display: "39.2 cm (15.6 inch) Display",
    productWarranty: "1 Year",
    carryonWarranty: "6 Month",
    operatingSystem: "Windows 11",
    ssd: "512 GB",
    wifi: "yes",
    price: "54,490",
    originalPrice: "82,789",
    offer: "34",
    freeDelivery: "yes",
    hotDeal: "yes",
    cashback: "25,000 ",
    bankOffer: "no",
    date: "17th Jan",
  },
  {
    number: 4,
    name: "Lenovo",
    nameDescription:
      "Lenovo IdeaPad Slim 5 WUXGA OLED AI PC Intel Core Ultra 5 125H - (16 GB/1 TB SSD/Windows 11 Home) 14IMH9 Laptop  (14 Inch, Cloud Grey, 1.46 Kg, With MS Office)",
    ratingStar: 4.1,
    ram: "16GB LPDDR5X RAM",
    size: "w-60 mt-10",
    ratingNumber: "456",
    reviewNumber: "1,163",
    img: "/ProductList/Lenovo.png",
    processor: "Intel Core Ultra 5 Processor",
    display: "35.56 cm (14 inch) Display",
    productWarranty: "1 Year",
    carryonWarranty: "1 Year",
    operatingSystem: "Windows 11",
    ssd: "1 TB",
    wifi: "yes",
    price: "84,999",
    originalPrice: "1,01,000",
    offer: "15",
    freeDelivery: "yes",
    hotDeal: "yes",
    cashback: "25,000 ",
    bankOffer: "no",
    date: "17th Jan",
  },
];

const REFRIGERATOR = [
  {
    number: 1,
    name: "Haier",
    nameDescription:
      "Haier 237 L Frost Free Double Door 2 Star Convertible Refrigerator with Convertible 8-in-1Turbo Icing  (Moon Silver, HEB-242GS-P)",
    ratingStar: 4.4,
    ratingNumber: "5,706",
    size: "w-24",
    reviewNumber: "518",
    compressor: "Normal",
    stabilizer: "Built in Stabilizer",
    productWarranty: "1 Year",
    compressorWarranty: "10 Year",
    img: "/ProductList/HaierFridge.png",
    price: "23,489",
    originalPrice: "33,490",
    date: "Tomorrow",
    cashback: "5,350",
    hotDeal: "no",
    bankOffer: "yes",
    offer: "29",
  },
  {
    number: 2,
    name: "whirlpool",
    nameDescription:
      "Whirlpool 235 L Frost Free Triple Door Refrigerator  (Radiant Steel, FP 253D PROTTON ROY RADIANT STEEL(Z))",
    ratingStar: 4.3,
    ratingNumber: "39,253",
    size: "w-24",
    reviewNumber: "4,261",
    compressor: "Reciprocating",
    stabilizer: "Built in Stabilizer",
    productWarranty: "1 Year",
    compressorWarranty: "9 Year",
    img: "/ProductList/whirlpool.png",
    price: "25,990",
    originalPrice: "35,380",
    date: "Tomorrow",
    cashback: "5,350",
    hotDeal: "yes",
    bankOffer: "no",
    offer: "27",
  },
  {
    number: 3,
    name: "samsung",
    nameDescription:
      "SAMSUNG 236 L Frost Free Double Door 3 Star Convertible Refrigerator with Digital Inverter and Display  (Black DOI, RT28C3733B1/HL)",
    ratingStar: 4.4,
    ratingNumber: "19,545",
    size: "w-24",
    reviewNumber: "1,414",
    compressor: "Digital Inverter",
    stabilizer: "Built in Stabilizer",
    productWarranty: "1 Year",
    compressorWarranty: "20 Year",
    img: "/ProductList/samsungFridge.png",
    price: "26,990",
    originalPrice: "41,990",
    offer: "35",
    date: "Tomorrow",
    cashback: "5,350",
    hotDeal: "no",
    bankOffer: "yes",
  },
  {
    number: 4,
    name: "LG",
    nameDescription:
      "LG 398 L Frost Free Double Door 3 Star Convertible Refrigerator with Smart Inverter Compressor  (Shiny Steel, GL-S422SPZX)",
    ratingStar: 4.4,
    ratingNumber: "20,979",
    size: "w-24",
    reviewNumber: "1,700",
    compressor: "Smart Inverter",
    stabilizer: "Built in Stabilizer",
    productWarranty: "1 Year",
    compressorWarranty: "10 Year",
    img: "/ProductList/LGFridge.png",
    price: "44,990",
    originalPrice: "60,899",
    date: "Tomorrow",
    cashback: "5,350",
    hotDeal: "no",
    bankOffer: "yes",
    offer: "26",
  },
];

const SMART = [
  {
    number: 1,
    nameDescription:
      "Alexa Echo Dot (5th Gen)| Bluetooth with Alexa Assistant Smart Speaker  (Black)",
    ratingStar: 4.2,
    ratingNumber: "261",
    size: "w-52 mb-1 mx-auto",
    reviewNumber: "1,700",
    img: "/ProductList/Alexa.png",
    price: "5,499",
    bankOffer: "",
    cashback: "",
    offer: "",
    hotDeal: "",
    color: "Black",
    freeDelivery: "yes",
  },
  {
    number: 2,
    nameDescription:
      "Smartlife WiFi 24A Touch Glass Smart Switch (Black) | No Hub Required Smart Switch  (Black)",
    color: "Black",
    ratingNumber: "261",
    size: "w-52 mb-7 mx-auto",
    reviewNumber: "1,700",
    img: "/ProductList/SmartLife.png",
    price: "5,499",
    bankOffer: "no",
    originalPrice: "10,980",
    cashback: "",
    offer: "50",
    hotDeal: "no",
    freeDelivery: "yes",
  },
  {
    number: 3,
    nameDescription:
      "SiSAH 3 Way Wall Capacitive Touch Switch Smart Switch  (Black)",
    ratingStar: 3,
    ratingNumber: "6",
    size: "w-52 mb-2 mx-auto",
    reviewNumber: "1,700",
    img: "/ProductList/sisah.png",
    price: "1,399",
    originalPrice: "2,199",
    bankOffer: "36",
    cashback: "",
    offer: "36",
    hotDeal: "",
    freeDelivery: "yes",
    color: "Black",
  },
  {
    number: 4,
    nameDescription:
      "Braevo 248.92 cm (98 inch) 4K Ultra HD OLED Panel Monitor (4K Smart Flat Panel 98 Inch MultiTouch Android 13 with Window 8GB RAM 128GB SSD)  (Response Time: 4 ms, 60 Hz Refresh Rate)",
    ratingStar: 4.2,
    ratingNumber: "261",
    size: "w-64 mb-7 mx-auto",
    reviewNumber: "1,700",
    img: "/ProductList/Braevo.png",
    price: "2,39,499",
    originalPrice: "3,19,545",
    bankOffer: "",
    cashback: "",
    offer: "25",
    hotDeal: "",
    freeDelivery: "yes",
    color: "Response Time: 4 ms, 60 Hz Refresh Rate",
  },
  {
    number: 5,
    nameDescription:
      "Boss Projector PINAKA S15 Android (9000 lm / Wireless / Remote Controller) Portable Projector  (White)",

    size: "w-60 mb-3 mx-auto ",
    img: "/ProductList/Boss.png",
    price: "1,90,000",
    originalPrice: "5,99,999",
    bankOffer: "",
    cashback: "",
    offer: "68",
    hotDeal: "",
    freeDelivery: "yes",
    color: "White",
  },
  {
    number: 6,
    nameDescription:
      "Sonos Beam 2 Wireless Dolby Atmos, Wi-Fi Connect 250 W Bluetooth Soundbar  (Black, Stereo Channel)",
    ratingStar: 4.4,
    ratingNumber: "11",
    size: "w-80 mb-6 mx-auto",
    reviewNumber: "1,700",
    img: "/ProductList/Sonos.png",
    price: "51,297",
    originalPrice: "59,999",
    bankOffer: "",
    cashback: "",
    offer: "14",
    hotDeal: "",
    freeDelivery: "yes",
  },
  {
    number: 7,
    nameDescription: "PHILIPS AC4372/10 Portable Room Air Purifier  (White)",
    ratingStar: 4.5,
    ratingNumber: "13",
    size: "w-28 mb-1 mx-auto",
    reviewNumber: "1,700",
    img: "/ProductList/PhilipsSmart.png",
    price: "44,999",
    originalPrice: "49,995",
    bankOffer: "",
    cashback: "",
    offer: "9",
    hotDeal: "",
    freeDelivery: "yes",
  },
  {
    number: 8,
    nameDescription:
      "Panasonic 7 in 1 Convertible with True AI Mode 2 Ton 3 Star Split Inverter AC with Wi-fi Connect - White  (CS-SU24ZKYWA/CU-SU24ZKYWA, Copper Condenser)",
    ratingStar: 4.1,
    ratingNumber: "25,318",
    size: "w-70  py-12 md:mb-2 sm:mb-8 mx-auto",
    reviewNumber: "1,700",
    img: "/ProductList/Panasonic.png",
    price: "50,990",
    originalPrice: "69,490",
    bankOffer: "",
    date: "18th Jan",
    cashback: "",
    offer: "20",
    hotDeal: "",
    color: "CS-SU24ZKYWA/CU-SU24ZKYWA, Copper Condenser",
  },
];

export { AC, TV, Gadgets, HOME, KITCHEN, PC, REFRIGERATOR, SMART };
